# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _fmm
else:
    import _fmm

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _fmm.delete_SwigPyIterator

    def value(self):
        return _fmm.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _fmm.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _fmm.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _fmm.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _fmm.SwigPyIterator_equal(self, x)

    def copy(self):
        return _fmm.SwigPyIterator_copy(self)

    def next(self):
        return _fmm.SwigPyIterator_next(self)

    def __next__(self):
        return _fmm.SwigPyIterator___next__(self)

    def previous(self):
        return _fmm.SwigPyIterator_previous(self)

    def advance(self, n):
        return _fmm.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _fmm.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _fmm.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _fmm.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _fmm.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _fmm.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _fmm.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _fmm:
_fmm.SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _fmm.SHARED_PTR_DISOWN
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.IntVector___nonzero__(self)

    def __bool__(self):
        return _fmm.IntVector___bool__(self)

    def __len__(self):
        return _fmm.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.IntVector___setitem__(self, *args)

    def pop(self):
        return _fmm.IntVector_pop(self)

    def append(self, x):
        return _fmm.IntVector_append(self, x)

    def empty(self):
        return _fmm.IntVector_empty(self)

    def size(self):
        return _fmm.IntVector_size(self)

    def swap(self, v):
        return _fmm.IntVector_swap(self, v)

    def begin(self):
        return _fmm.IntVector_begin(self)

    def end(self):
        return _fmm.IntVector_end(self)

    def rbegin(self):
        return _fmm.IntVector_rbegin(self)

    def rend(self):
        return _fmm.IntVector_rend(self)

    def clear(self):
        return _fmm.IntVector_clear(self)

    def get_allocator(self):
        return _fmm.IntVector_get_allocator(self)

    def pop_back(self):
        return _fmm.IntVector_pop_back(self)

    def erase(self, *args):
        return _fmm.IntVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.IntVector_swiginit(self, _fmm.new_IntVector(*args))

    def push_back(self, x):
        return _fmm.IntVector_push_back(self, x)

    def front(self):
        return _fmm.IntVector_front(self)

    def back(self):
        return _fmm.IntVector_back(self)

    def assign(self, n, x):
        return _fmm.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.IntVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.IntVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.IntVector_reserve(self, n)

    def capacity(self):
        return _fmm.IntVector_capacity(self)
    __swig_destroy__ = _fmm.delete_IntVector

# Register IntVector in _fmm:
_fmm.IntVector_swigregister(IntVector)

class IDVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.IDVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.IDVector___nonzero__(self)

    def __bool__(self):
        return _fmm.IDVector___bool__(self)

    def __len__(self):
        return _fmm.IDVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.IDVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.IDVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.IDVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.IDVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.IDVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.IDVector___setitem__(self, *args)

    def pop(self):
        return _fmm.IDVector_pop(self)

    def append(self, x):
        return _fmm.IDVector_append(self, x)

    def empty(self):
        return _fmm.IDVector_empty(self)

    def size(self):
        return _fmm.IDVector_size(self)

    def swap(self, v):
        return _fmm.IDVector_swap(self, v)

    def begin(self):
        return _fmm.IDVector_begin(self)

    def end(self):
        return _fmm.IDVector_end(self)

    def rbegin(self):
        return _fmm.IDVector_rbegin(self)

    def rend(self):
        return _fmm.IDVector_rend(self)

    def clear(self):
        return _fmm.IDVector_clear(self)

    def get_allocator(self):
        return _fmm.IDVector_get_allocator(self)

    def pop_back(self):
        return _fmm.IDVector_pop_back(self)

    def erase(self, *args):
        return _fmm.IDVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.IDVector_swiginit(self, _fmm.new_IDVector(*args))

    def push_back(self, x):
        return _fmm.IDVector_push_back(self, x)

    def front(self):
        return _fmm.IDVector_front(self)

    def back(self):
        return _fmm.IDVector_back(self)

    def assign(self, n, x):
        return _fmm.IDVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.IDVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.IDVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.IDVector_reserve(self, n)

    def capacity(self):
        return _fmm.IDVector_capacity(self)
    __swig_destroy__ = _fmm.delete_IDVector

# Register IDVector in _fmm:
_fmm.IDVector_swigregister(IDVector)

class HexVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.HexVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.HexVector___nonzero__(self)

    def __bool__(self):
        return _fmm.HexVector___bool__(self)

    def __len__(self):
        return _fmm.HexVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.HexVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.HexVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.HexVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.HexVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.HexVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.HexVector___setitem__(self, *args)

    def pop(self):
        return _fmm.HexVector_pop(self)

    def append(self, x):
        return _fmm.HexVector_append(self, x)

    def empty(self):
        return _fmm.HexVector_empty(self)

    def size(self):
        return _fmm.HexVector_size(self)

    def swap(self, v):
        return _fmm.HexVector_swap(self, v)

    def begin(self):
        return _fmm.HexVector_begin(self)

    def end(self):
        return _fmm.HexVector_end(self)

    def rbegin(self):
        return _fmm.HexVector_rbegin(self)

    def rend(self):
        return _fmm.HexVector_rend(self)

    def clear(self):
        return _fmm.HexVector_clear(self)

    def get_allocator(self):
        return _fmm.HexVector_get_allocator(self)

    def pop_back(self):
        return _fmm.HexVector_pop_back(self)

    def erase(self, *args):
        return _fmm.HexVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.HexVector_swiginit(self, _fmm.new_HexVector(*args))

    def push_back(self, x):
        return _fmm.HexVector_push_back(self, x)

    def front(self):
        return _fmm.HexVector_front(self)

    def back(self):
        return _fmm.HexVector_back(self)

    def assign(self, n, x):
        return _fmm.HexVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.HexVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.HexVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.HexVector_reserve(self, n)

    def capacity(self):
        return _fmm.HexVector_capacity(self)
    __swig_destroy__ = _fmm.delete_HexVector

# Register HexVector in _fmm:
_fmm.HexVector_swigregister(HexVector)

class UnsignedIntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.UnsignedIntVector___nonzero__(self)

    def __bool__(self):
        return _fmm.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _fmm.UnsignedIntVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.UnsignedIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.UnsignedIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.UnsignedIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _fmm.UnsignedIntVector_pop(self)

    def append(self, x):
        return _fmm.UnsignedIntVector_append(self, x)

    def empty(self):
        return _fmm.UnsignedIntVector_empty(self)

    def size(self):
        return _fmm.UnsignedIntVector_size(self)

    def swap(self, v):
        return _fmm.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _fmm.UnsignedIntVector_begin(self)

    def end(self):
        return _fmm.UnsignedIntVector_end(self)

    def rbegin(self):
        return _fmm.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _fmm.UnsignedIntVector_rend(self)

    def clear(self):
        return _fmm.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _fmm.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _fmm.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _fmm.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.UnsignedIntVector_swiginit(self, _fmm.new_UnsignedIntVector(*args))

    def push_back(self, x):
        return _fmm.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _fmm.UnsignedIntVector_front(self)

    def back(self):
        return _fmm.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _fmm.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _fmm.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _fmm.delete_UnsignedIntVector

# Register UnsignedIntVector in _fmm:
_fmm.UnsignedIntVector_swigregister(UnsignedIntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _fmm.DoubleVector___bool__(self)

    def __len__(self):
        return _fmm.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _fmm.DoubleVector_pop(self)

    def append(self, x):
        return _fmm.DoubleVector_append(self, x)

    def empty(self):
        return _fmm.DoubleVector_empty(self)

    def size(self):
        return _fmm.DoubleVector_size(self)

    def swap(self, v):
        return _fmm.DoubleVector_swap(self, v)

    def begin(self):
        return _fmm.DoubleVector_begin(self)

    def end(self):
        return _fmm.DoubleVector_end(self)

    def rbegin(self):
        return _fmm.DoubleVector_rbegin(self)

    def rend(self):
        return _fmm.DoubleVector_rend(self)

    def clear(self):
        return _fmm.DoubleVector_clear(self)

    def get_allocator(self):
        return _fmm.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _fmm.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _fmm.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.DoubleVector_swiginit(self, _fmm.new_DoubleVector(*args))

    def push_back(self, x):
        return _fmm.DoubleVector_push_back(self, x)

    def front(self):
        return _fmm.DoubleVector_front(self)

    def back(self):
        return _fmm.DoubleVector_back(self)

    def assign(self, n, x):
        return _fmm.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.DoubleVector_reserve(self, n)

    def capacity(self):
        return _fmm.DoubleVector_capacity(self)
    __swig_destroy__ = _fmm.delete_DoubleVector

# Register DoubleVector in _fmm:
_fmm.DoubleVector_swigregister(DoubleVector)

class DoubleVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.DoubleVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.DoubleVectorVector___nonzero__(self)

    def __bool__(self):
        return _fmm.DoubleVectorVector___bool__(self)

    def __len__(self):
        return _fmm.DoubleVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.DoubleVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.DoubleVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.DoubleVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.DoubleVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.DoubleVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.DoubleVectorVector___setitem__(self, *args)

    def pop(self):
        return _fmm.DoubleVectorVector_pop(self)

    def append(self, x):
        return _fmm.DoubleVectorVector_append(self, x)

    def empty(self):
        return _fmm.DoubleVectorVector_empty(self)

    def size(self):
        return _fmm.DoubleVectorVector_size(self)

    def swap(self, v):
        return _fmm.DoubleVectorVector_swap(self, v)

    def begin(self):
        return _fmm.DoubleVectorVector_begin(self)

    def end(self):
        return _fmm.DoubleVectorVector_end(self)

    def rbegin(self):
        return _fmm.DoubleVectorVector_rbegin(self)

    def rend(self):
        return _fmm.DoubleVectorVector_rend(self)

    def clear(self):
        return _fmm.DoubleVectorVector_clear(self)

    def get_allocator(self):
        return _fmm.DoubleVectorVector_get_allocator(self)

    def pop_back(self):
        return _fmm.DoubleVectorVector_pop_back(self)

    def erase(self, *args):
        return _fmm.DoubleVectorVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.DoubleVectorVector_swiginit(self, _fmm.new_DoubleVectorVector(*args))

    def push_back(self, x):
        return _fmm.DoubleVectorVector_push_back(self, x)

    def front(self):
        return _fmm.DoubleVectorVector_front(self)

    def back(self):
        return _fmm.DoubleVectorVector_back(self)

    def assign(self, n, x):
        return _fmm.DoubleVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.DoubleVectorVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.DoubleVectorVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.DoubleVectorVector_reserve(self, n)

    def capacity(self):
        return _fmm.DoubleVectorVector_capacity(self)
    __swig_destroy__ = _fmm.delete_DoubleVectorVector

# Register DoubleVectorVector in _fmm:
_fmm.DoubleVectorVector_swigregister(DoubleVectorVector)

class PyCandidateVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.PyCandidateVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.PyCandidateVector___nonzero__(self)

    def __bool__(self):
        return _fmm.PyCandidateVector___bool__(self)

    def __len__(self):
        return _fmm.PyCandidateVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.PyCandidateVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.PyCandidateVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.PyCandidateVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.PyCandidateVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.PyCandidateVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.PyCandidateVector___setitem__(self, *args)

    def pop(self):
        return _fmm.PyCandidateVector_pop(self)

    def append(self, x):
        return _fmm.PyCandidateVector_append(self, x)

    def empty(self):
        return _fmm.PyCandidateVector_empty(self)

    def size(self):
        return _fmm.PyCandidateVector_size(self)

    def swap(self, v):
        return _fmm.PyCandidateVector_swap(self, v)

    def begin(self):
        return _fmm.PyCandidateVector_begin(self)

    def end(self):
        return _fmm.PyCandidateVector_end(self)

    def rbegin(self):
        return _fmm.PyCandidateVector_rbegin(self)

    def rend(self):
        return _fmm.PyCandidateVector_rend(self)

    def clear(self):
        return _fmm.PyCandidateVector_clear(self)

    def get_allocator(self):
        return _fmm.PyCandidateVector_get_allocator(self)

    def pop_back(self):
        return _fmm.PyCandidateVector_pop_back(self)

    def erase(self, *args):
        return _fmm.PyCandidateVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.PyCandidateVector_swiginit(self, _fmm.new_PyCandidateVector(*args))

    def push_back(self, x):
        return _fmm.PyCandidateVector_push_back(self, x)

    def front(self):
        return _fmm.PyCandidateVector_front(self)

    def back(self):
        return _fmm.PyCandidateVector_back(self)

    def assign(self, n, x):
        return _fmm.PyCandidateVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.PyCandidateVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.PyCandidateVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.PyCandidateVector_reserve(self, n)

    def capacity(self):
        return _fmm.PyCandidateVector_capacity(self)
    __swig_destroy__ = _fmm.delete_PyCandidateVector

# Register PyCandidateVector in _fmm:
_fmm.PyCandidateVector_swigregister(PyCandidateVector)

class CovarianceMatrixVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.CovarianceMatrixVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.CovarianceMatrixVector___nonzero__(self)

    def __bool__(self):
        return _fmm.CovarianceMatrixVector___bool__(self)

    def __len__(self):
        return _fmm.CovarianceMatrixVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.CovarianceMatrixVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.CovarianceMatrixVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.CovarianceMatrixVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.CovarianceMatrixVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.CovarianceMatrixVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.CovarianceMatrixVector___setitem__(self, *args)

    def pop(self):
        return _fmm.CovarianceMatrixVector_pop(self)

    def append(self, x):
        return _fmm.CovarianceMatrixVector_append(self, x)

    def empty(self):
        return _fmm.CovarianceMatrixVector_empty(self)

    def size(self):
        return _fmm.CovarianceMatrixVector_size(self)

    def swap(self, v):
        return _fmm.CovarianceMatrixVector_swap(self, v)

    def begin(self):
        return _fmm.CovarianceMatrixVector_begin(self)

    def end(self):
        return _fmm.CovarianceMatrixVector_end(self)

    def rbegin(self):
        return _fmm.CovarianceMatrixVector_rbegin(self)

    def rend(self):
        return _fmm.CovarianceMatrixVector_rend(self)

    def clear(self):
        return _fmm.CovarianceMatrixVector_clear(self)

    def get_allocator(self):
        return _fmm.CovarianceMatrixVector_get_allocator(self)

    def pop_back(self):
        return _fmm.CovarianceMatrixVector_pop_back(self)

    def erase(self, *args):
        return _fmm.CovarianceMatrixVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.CovarianceMatrixVector_swiginit(self, _fmm.new_CovarianceMatrixVector(*args))

    def push_back(self, x):
        return _fmm.CovarianceMatrixVector_push_back(self, x)

    def front(self):
        return _fmm.CovarianceMatrixVector_front(self)

    def back(self):
        return _fmm.CovarianceMatrixVector_back(self)

    def assign(self, n, x):
        return _fmm.CovarianceMatrixVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.CovarianceMatrixVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.CovarianceMatrixVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.CovarianceMatrixVector_reserve(self, n)

    def capacity(self):
        return _fmm.CovarianceMatrixVector_capacity(self)
    __swig_destroy__ = _fmm.delete_CovarianceMatrixVector

# Register CovarianceMatrixVector in _fmm:
_fmm.CovarianceMatrixVector_swigregister(CovarianceMatrixVector)

class IntVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _fmm.IntVectorVector___bool__(self)

    def __len__(self):
        return _fmm.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _fmm.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _fmm.IntVectorVector_pop(self)

    def append(self, x):
        return _fmm.IntVectorVector_append(self, x)

    def empty(self):
        return _fmm.IntVectorVector_empty(self)

    def size(self):
        return _fmm.IntVectorVector_size(self)

    def swap(self, v):
        return _fmm.IntVectorVector_swap(self, v)

    def begin(self):
        return _fmm.IntVectorVector_begin(self)

    def end(self):
        return _fmm.IntVectorVector_end(self)

    def rbegin(self):
        return _fmm.IntVectorVector_rbegin(self)

    def rend(self):
        return _fmm.IntVectorVector_rend(self)

    def clear(self):
        return _fmm.IntVectorVector_clear(self)

    def get_allocator(self):
        return _fmm.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _fmm.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _fmm.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        _fmm.IntVectorVector_swiginit(self, _fmm.new_IntVectorVector(*args))

    def push_back(self, x):
        return _fmm.IntVectorVector_push_back(self, x)

    def front(self):
        return _fmm.IntVectorVector_front(self)

    def back(self):
        return _fmm.IntVectorVector_back(self)

    def assign(self, n, x):
        return _fmm.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _fmm.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _fmm.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _fmm.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _fmm.IntVectorVector_capacity(self)
    __swig_destroy__ = _fmm.delete_IntVectorVector

# Register IntVectorVector in _fmm:
_fmm.IntVectorVector_swigregister(IntVectorVector)

class MatchedCandidatePath(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _fmm.MatchedCandidatePath_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fmm.MatchedCandidatePath___nonzero__(self)

    def __bool__(self):
        return _fmm.MatchedCandidatePath___bool__(self)

    def __len__(self):
        return _fmm.MatchedCandidatePath___len__(self)

    def __getslice__(self, i, j):
        return _fmm.MatchedCandidatePath___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fmm.MatchedCandidatePath___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fmm.MatchedCandidatePath___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fmm.MatchedCandidatePath___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fmm.MatchedCandidatePath___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fmm.MatchedCandidatePath___setitem__(self, *args)

    def pop(self):
        return _fmm.MatchedCandidatePath_pop(self)

    def append(self, x):
        return _fmm.MatchedCandidatePath_append(self, x)

    def empty(self):
        return _fmm.MatchedCandidatePath_empty(self)

    def size(self):
        return _fmm.MatchedCandidatePath_size(self)

    def swap(self, v):
        return _fmm.MatchedCandidatePath_swap(self, v)

    def begin(self):
        return _fmm.MatchedCandidatePath_begin(self)

    def end(self):
        return _fmm.MatchedCandidatePath_end(self)

    def rbegin(self):
        return _fmm.MatchedCandidatePath_rbegin(self)

    def rend(self):
        return _fmm.MatchedCandidatePath_rend(self)

    def clear(self):
        return _fmm.MatchedCandidatePath_clear(self)

    def get_allocator(self):
        return _fmm.MatchedCandidatePath_get_allocator(self)

    def pop_back(self):
        return _fmm.MatchedCandidatePath_pop_back(self)

    def erase(self, *args):
        return _fmm.MatchedCandidatePath_erase(self, *args)

    def __init__(self, *args):
        _fmm.MatchedCandidatePath_swiginit(self, _fmm.new_MatchedCandidatePath(*args))

    def push_back(self, x):
        return _fmm.MatchedCandidatePath_push_back(self, x)

    def front(self):
        return _fmm.MatchedCandidatePath_front(self)

    def back(self):
        return _fmm.MatchedCandidatePath_back(self)

    def assign(self, n, x):
        return _fmm.MatchedCandidatePath_assign(self, n, x)

    def resize(self, *args):
        return _fmm.MatchedCandidatePath_resize(self, *args)

    def insert(self, *args):
        return _fmm.MatchedCandidatePath_insert(self, *args)

    def reserve(self, n):
        return _fmm.MatchedCandidatePath_reserve(self, n)

    def capacity(self):
        return _fmm.MatchedCandidatePath_capacity(self)
    __swig_destroy__ = _fmm.delete_MatchedCandidatePath

# Register MatchedCandidatePath in _fmm:
_fmm.MatchedCandidatePath_swigregister(MatchedCandidatePath)

class LineString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def get_x(self, i):
        return _fmm.LineString_get_x(self, i)

    def get_y(self, i):
        return _fmm.LineString_get_y(self, i)

    def set_x(self, i, v):
        return _fmm.LineString_set_x(self, i, v)

    def set_y(self, i, v):
        return _fmm.LineString_set_y(self, i, v)

    def add_point(self, *args):
        return _fmm.LineString_add_point(self, *args)

    def get_point(self, i):
        return _fmm.LineString_get_point(self, i)

    def at(self, i):
        return _fmm.LineString_at(self, i)

    def get_num_points(self):
        return _fmm.LineString_get_num_points(self)

    def is_empty(self):
        return _fmm.LineString_is_empty(self)

    def clear(self):
        return _fmm.LineString_clear(self)

    def get_length(self):
        return _fmm.LineString_get_length(self)

    def export_wkt(self, precision=8):
        return _fmm.LineString_export_wkt(self, precision)

    def export_json(self):
        return _fmm.LineString_export_json(self)

    def get_geometry_const(self):
        return _fmm.LineString_get_geometry_const(self)

    def get_geometry(self):
        return _fmm.LineString_get_geometry(self)

    def __eq__(self, rhs):
        return _fmm.LineString___eq__(self, rhs)

    def __init__(self):
        _fmm.LineString_swiginit(self, _fmm.new_LineString())
    __swig_destroy__ = _fmm.delete_LineString

# Register LineString in _fmm:
_fmm.LineString_swigregister(LineString)


def __lshift__(os, rhs):
    return _fmm.__lshift__(os, rhs)

def ogr2linestring(*args):
    return _fmm.ogr2linestring(*args)

def wkt2linestring(wkt):
    return _fmm.wkt2linestring(wkt)
class Trajectory(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _fmm.Trajectory_swiginit(self, _fmm.new_Trajectory(*args))
    id = property(_fmm.Trajectory_id_get, _fmm.Trajectory_id_set)
    geom = property(_fmm.Trajectory_geom_get, _fmm.Trajectory_geom_set)
    timestamps = property(_fmm.Trajectory_timestamps_get, _fmm.Trajectory_timestamps_set)
    __swig_destroy__ = _fmm.delete_Trajectory

# Register Trajectory in _fmm:
_fmm.Trajectory_swigregister(Trajectory)

class Candidate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    index = property(_fmm.Candidate_index_get, _fmm.Candidate_index_set)
    offset = property(_fmm.Candidate_offset_get, _fmm.Candidate_offset_set)
    dist = property(_fmm.Candidate_dist_get, _fmm.Candidate_dist_set)
    edge = property(_fmm.Candidate_edge_get, _fmm.Candidate_edge_set)
    point = property(_fmm.Candidate_point_get, _fmm.Candidate_point_set)

    def __init__(self):
        _fmm.Candidate_swiginit(self, _fmm.new_Candidate())
    __swig_destroy__ = _fmm.delete_Candidate

# Register Candidate in _fmm:
_fmm.Candidate_swigregister(Candidate)

class CandidateEmission(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_fmm.CandidateEmission_x_get, _fmm.CandidateEmission_x_set)
    y = property(_fmm.CandidateEmission_y_get, _fmm.CandidateEmission_y_set)
    ep = property(_fmm.CandidateEmission_ep_get, _fmm.CandidateEmission_ep_set)

    def __init__(self):
        _fmm.CandidateEmission_swiginit(self, _fmm.new_CandidateEmission())
    __swig_destroy__ = _fmm.delete_CandidateEmission

# Register CandidateEmission in _fmm:
_fmm.CandidateEmission_swigregister(CandidateEmission)

class MatchedCandidate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    c = property(_fmm.MatchedCandidate_c_get, _fmm.MatchedCandidate_c_set)
    ep = property(_fmm.MatchedCandidate_ep_get, _fmm.MatchedCandidate_ep_set)
    tp = property(_fmm.MatchedCandidate_tp_get, _fmm.MatchedCandidate_tp_set)
    cumu_prob = property(_fmm.MatchedCandidate_cumu_prob_get, _fmm.MatchedCandidate_cumu_prob_set)
    sp_dist = property(_fmm.MatchedCandidate_sp_dist_get, _fmm.MatchedCandidate_sp_dist_set)
    trustworthiness = property(_fmm.MatchedCandidate_trustworthiness_get, _fmm.MatchedCandidate_trustworthiness_set)

    def __init__(self):
        _fmm.MatchedCandidate_swiginit(self, _fmm.new_MatchedCandidate())
    __swig_destroy__ = _fmm.delete_MatchedCandidate

# Register MatchedCandidate in _fmm:
_fmm.MatchedCandidate_swigregister(MatchedCandidate)

class MatchResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_fmm.MatchResult_id_get, _fmm.MatchResult_id_set)
    opt_candidate_path = property(_fmm.MatchResult_opt_candidate_path_get, _fmm.MatchResult_opt_candidate_path_set)
    opath = property(_fmm.MatchResult_opath_get, _fmm.MatchResult_opath_set)
    cpath = property(_fmm.MatchResult_cpath_get, _fmm.MatchResult_cpath_set)
    indices = property(_fmm.MatchResult_indices_get, _fmm.MatchResult_indices_set)
    mgeom = property(_fmm.MatchResult_mgeom_get, _fmm.MatchResult_mgeom_set)
    candidate_details = property(_fmm.MatchResult_candidate_details_get, _fmm.MatchResult_candidate_details_set)
    nbest_trustworthiness = property(_fmm.MatchResult_nbest_trustworthiness_get, _fmm.MatchResult_nbest_trustworthiness_set)
    sp_distances = property(_fmm.MatchResult_sp_distances_get, _fmm.MatchResult_sp_distances_set)
    eu_distances = property(_fmm.MatchResult_eu_distances_get, _fmm.MatchResult_eu_distances_set)

    def __init__(self):
        _fmm.MatchResult_swiginit(self, _fmm.new_MatchResult())
    __swig_destroy__ = _fmm.delete_MatchResult

# Register MatchResult in _fmm:
_fmm.MatchResult_swigregister(MatchResult)

class Edge(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    index = property(_fmm.Edge_index_get, _fmm.Edge_index_set)
    id = property(_fmm.Edge_id_get, _fmm.Edge_id_set)
    source = property(_fmm.Edge_source_get, _fmm.Edge_source_set)
    target = property(_fmm.Edge_target_get, _fmm.Edge_target_set)
    length = property(_fmm.Edge_length_get, _fmm.Edge_length_set)
    geom = property(_fmm.Edge_geom_get, _fmm.Edge_geom_set)

    def __init__(self):
        _fmm.Edge_swiginit(self, _fmm.new_Edge())
    __swig_destroy__ = _fmm.delete_Edge

# Register Edge in _fmm:
_fmm.Edge_swigregister(Edge)

class Network(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _fmm.Network_swiginit(self, _fmm.new_Network(*args))

    def get_node_count(self):
        return _fmm.Network_get_node_count(self)

    def get_edge_count(self):
        return _fmm.Network_get_edge_count(self)

    def get_edge(self, id):
        return _fmm.Network_get_edge(self, id)

    def get_edges(self):
        return _fmm.Network_get_edges(self)

    def get_edge_id(self, index):
        return _fmm.Network_get_edge_id(self, index)

    def get_edge_index(self, id):
        return _fmm.Network_get_edge_index(self, id)

    def get_node_id(self, index):
        return _fmm.Network_get_node_id(self, index)

    def get_node_index(self, id):
        return _fmm.Network_get_node_index(self, id)

    def get_node_geom_from_idx(self, index):
        return _fmm.Network_get_node_geom_from_idx(self, index)

    def search_tr_cs_knn(self, *args):
        return _fmm.Network_search_tr_cs_knn(self, *args)

    def get_edge_geom(self, edge_id):
        return _fmm.Network_get_edge_geom(self, edge_id)

    def complete_path_to_geometry(self, traj, complete_path):
        return _fmm.Network_complete_path_to_geometry(self, traj, complete_path)

    def get_vertex_points(self):
        return _fmm.Network_get_vertex_points(self)

    def get_vertex_point(self, u):
        return _fmm.Network_get_vertex_point(self, u)

    def route2geometry(self, path):
        return _fmm.Network_route2geometry(self, path)

    @staticmethod
    def candidate_compare(a, b):
        return _fmm.Network_candidate_compare(a, b)

    def add_edge(self, edge_id, source, target, geom):
        return _fmm.Network_add_edge(self, edge_id, source, target, geom)

    def is_projected(self):
        return _fmm.Network_is_projected(self)

    def has_spatial_ref(self):
        return _fmm.Network_has_spatial_ref(self)

    def get_spatial_ref_wkt(self):
        return _fmm.Network_get_spatial_ref_wkt(self)

    def was_reprojected(self):
        return _fmm.Network_was_reprojected(self)
    __swig_destroy__ = _fmm.delete_Network

# Register Network in _fmm:
_fmm.Network_swigregister(Network)

def Network_candidate_compare(a, b):
    return _fmm.Network_candidate_compare(a, b)

class PyCandidate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    index = property(_fmm.PyCandidate_index_get, _fmm.PyCandidate_index_set)
    edge_id = property(_fmm.PyCandidate_edge_id_get, _fmm.PyCandidate_edge_id_set)
    source = property(_fmm.PyCandidate_source_get, _fmm.PyCandidate_source_set)
    target = property(_fmm.PyCandidate_target_get, _fmm.PyCandidate_target_set)
    error = property(_fmm.PyCandidate_error_get, _fmm.PyCandidate_error_set)
    offset = property(_fmm.PyCandidate_offset_get, _fmm.PyCandidate_offset_set)
    length = property(_fmm.PyCandidate_length_get, _fmm.PyCandidate_length_set)
    ep = property(_fmm.PyCandidate_ep_get, _fmm.PyCandidate_ep_set)
    tp = property(_fmm.PyCandidate_tp_get, _fmm.PyCandidate_tp_set)
    spdist = property(_fmm.PyCandidate_spdist_get, _fmm.PyCandidate_spdist_set)

    def __init__(self):
        _fmm.PyCandidate_swiginit(self, _fmm.new_PyCandidate())
    __swig_destroy__ = _fmm.delete_PyCandidate

# Register PyCandidate in _fmm:
_fmm.PyCandidate_swigregister(PyCandidate)

class PyMatchResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_fmm.PyMatchResult_id_get, _fmm.PyMatchResult_id_set)
    opath = property(_fmm.PyMatchResult_opath_get, _fmm.PyMatchResult_opath_set)
    cpath = property(_fmm.PyMatchResult_cpath_get, _fmm.PyMatchResult_cpath_set)
    candidates = property(_fmm.PyMatchResult_candidates_get, _fmm.PyMatchResult_candidates_set)
    indices = property(_fmm.PyMatchResult_indices_get, _fmm.PyMatchResult_indices_set)
    mgeom = property(_fmm.PyMatchResult_mgeom_get, _fmm.PyMatchResult_mgeom_set)
    pgeom = property(_fmm.PyMatchResult_pgeom_get, _fmm.PyMatchResult_pgeom_set)

    def __init__(self):
        _fmm.PyMatchResult_swiginit(self, _fmm.new_PyMatchResult())
    __swig_destroy__ = _fmm.delete_PyMatchResult

# Register PyMatchResult in _fmm:
_fmm.PyMatchResult_swigregister(PyMatchResult)

class Record(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    source = property(_fmm.Record_source_get, _fmm.Record_source_set)
    target = property(_fmm.Record_target_get, _fmm.Record_target_set)
    first_n = property(_fmm.Record_first_n_get, _fmm.Record_first_n_set)
    prev_n = property(_fmm.Record_prev_n_get, _fmm.Record_prev_n_set)
    next_e = property(_fmm.Record_next_e_get, _fmm.Record_next_e_set)
    cost = property(_fmm.Record_cost_get, _fmm.Record_cost_set)
    next = property(_fmm.Record_next_get, _fmm.Record_next_set)

    def __init__(self):
        _fmm.Record_swiginit(self, _fmm.new_Record())
    __swig_destroy__ = _fmm.delete_Record

# Register Record in _fmm:
_fmm.Record_swigregister(Record)

class UBODT(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, buckets_arg, multiplier_arg):
        _fmm.UBODT_swiginit(self, _fmm.new_UBODT(buckets_arg, multiplier_arg))
    __swig_destroy__ = _fmm.delete_UBODT

    def look_up(self, source, target):
        return _fmm.UBODT_look_up(self, source, target)

    def look_sp_path(self, source, target):
        return _fmm.UBODT_look_sp_path(self, source, target)

    def construct_complete_path(self, traj_id, path, edges, indices, reverse_tolerance):
        return _fmm.UBODT_construct_complete_path(self, traj_id, path, edges, indices, reverse_tolerance)

    def get_delta(self):
        return _fmm.UBODT_get_delta(self)

    def cal_bucket_index(self, source, target):
        return _fmm.UBODT_cal_bucket_index(self, source, target)

    def insert(self, r):
        return _fmm.UBODT_insert(self, r)

    def get_num_rows(self):
        return _fmm.UBODT_get_num_rows(self)

    def update_delta(self, value):
        return _fmm.UBODT_update_delta(self, value)

    @staticmethod
    def read_ubodt_file(filename, multiplier=50000):
        return _fmm.UBODT_read_ubodt_file(filename, multiplier)

    @staticmethod
    def read_ubodt_csv(filename, multiplier=50000):
        return _fmm.UBODT_read_ubodt_csv(filename, multiplier)

    @staticmethod
    def read_ubodt_binary(filename, multiplier=50000):
        return _fmm.UBODT_read_ubodt_binary(filename, multiplier)

    @staticmethod
    def read_ubodt_mmap_binary(filename, multiplier=50000):
        return _fmm.UBODT_read_ubodt_mmap_binary(filename, multiplier)

    @staticmethod
    def read_ubodt_indexed_binary(filename, multiplier=50000):
        return _fmm.UBODT_read_ubodt_indexed_binary(filename, multiplier)

    @staticmethod
    def estimate_ubodt_rows(filename):
        return _fmm.UBODT_estimate_ubodt_rows(filename)

    @staticmethod
    def find_prime_number(value):
        return _fmm.UBODT_find_prime_number(value)

    @staticmethod
    def is_mmap_binary_format(filename):
        return _fmm.UBODT_is_mmap_binary_format(filename)

    @staticmethod
    def is_indexed_binary_format(filename, record_count=None, source_count=None, header_size=None):
        return _fmm.UBODT_is_indexed_binary_format(filename, record_count, source_count, header_size)
    LOAD_FACTOR = _fmm.UBODT_LOAD_FACTOR
    BUFFER_LINE = _fmm.UBODT_BUFFER_LINE

# Register UBODT in _fmm:
_fmm.UBODT_swigregister(UBODT)

def UBODT_read_ubodt_file(filename, multiplier=50000):
    return _fmm.UBODT_read_ubodt_file(filename, multiplier)

def UBODT_read_ubodt_csv(filename, multiplier=50000):
    return _fmm.UBODT_read_ubodt_csv(filename, multiplier)

def UBODT_read_ubodt_binary(filename, multiplier=50000):
    return _fmm.UBODT_read_ubodt_binary(filename, multiplier)

def UBODT_read_ubodt_mmap_binary(filename, multiplier=50000):
    return _fmm.UBODT_read_ubodt_mmap_binary(filename, multiplier)

def UBODT_read_ubodt_indexed_binary(filename, multiplier=50000):
    return _fmm.UBODT_read_ubodt_indexed_binary(filename, multiplier)

def UBODT_estimate_ubodt_rows(filename):
    return _fmm.UBODT_estimate_ubodt_rows(filename)

def UBODT_find_prime_number(value):
    return _fmm.UBODT_find_prime_number(value)

def UBODT_is_mmap_binary_format(filename):
    return _fmm.UBODT_is_mmap_binary_format(filename)

def UBODT_is_indexed_binary_format(filename, record_count=None, source_count=None, header_size=None):
    return _fmm.UBODT_is_indexed_binary_format(filename, record_count, source_count, header_size)

class NetworkGraph(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, network_arg):
        _fmm.NetworkGraph_swiginit(self, _fmm.new_NetworkGraph(network_arg))

    def shortest_path_dijkstra(self, source, target):
        return _fmm.NetworkGraph_shortest_path_dijkstra(self, source, target)

    def calc_heuristic_dist(self, p1, p2):
        return _fmm.NetworkGraph_calc_heuristic_dist(self, p1, p2)

    def shortest_path_astar(self, source, target):
        return _fmm.NetworkGraph_shortest_path_astar(self, source, target)

    def back_track(self, source, target, pmap, dmap):
        return _fmm.NetworkGraph_back_track(self, source, target, pmap, dmap)

    def single_source_upperbound_dijkstra(self, source, delta, pmap, dmap):
        return _fmm.NetworkGraph_single_source_upperbound_dijkstra(self, source, delta, pmap, dmap)

    def single_source_upperbound_astar(self, source, delta, pmap, dmap, target=0):
        return _fmm.NetworkGraph_single_source_upperbound_astar(self, source, delta, pmap, dmap, target)

    def get_edge_index(self, *args):
        return _fmm.NetworkGraph_get_edge_index(self, *args)

    def get_edge(self, *args):
        return _fmm.NetworkGraph_get_edge(self, *args)

    def get_edge_id(self, *args):
        return _fmm.NetworkGraph_get_edge_id(self, *args)

    def get_node_id(self, idx):
        return _fmm.NetworkGraph_get_node_id(self, idx)

    def get_node_index(self, id):
        return _fmm.NetworkGraph_get_node_index(self, id)

    def get_vertex_point(self, u):
        return _fmm.NetworkGraph_get_vertex_point(self, u)

    def print_graph(self):
        return _fmm.NetworkGraph_print_graph(self)

    def get_boost_graph(self):
        return _fmm.NetworkGraph_get_boost_graph(self)

    def get_network(self):
        return _fmm.NetworkGraph_get_network(self)

    def get_num_vertices(self):
        return _fmm.NetworkGraph_get_num_vertices(self)
    __swig_destroy__ = _fmm.delete_NetworkGraph

# Register NetworkGraph in _fmm:
_fmm.NetworkGraph_swigregister(NetworkGraph)

class FastMapMatchConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, k_arg=8, r_arg=300, gps_error=50, reverse_tolerance=0.0):
        _fmm.FastMapMatchConfig_swiginit(self, _fmm.new_FastMapMatchConfig(k_arg, r_arg, gps_error, reverse_tolerance))
    k = property(_fmm.FastMapMatchConfig_k_get, _fmm.FastMapMatchConfig_k_set)
    radius = property(_fmm.FastMapMatchConfig_radius_get, _fmm.FastMapMatchConfig_radius_set)
    gps_error = property(_fmm.FastMapMatchConfig_gps_error_get, _fmm.FastMapMatchConfig_gps_error_set)
    reverse_tolerance = property(_fmm.FastMapMatchConfig_reverse_tolerance_get, _fmm.FastMapMatchConfig_reverse_tolerance_set)

    def validate(self):
        return _fmm.FastMapMatchConfig_validate(self)

    @staticmethod
    def load_from_xml(xml_data):
        return _fmm.FastMapMatchConfig_load_from_xml(xml_data)

    @staticmethod
    def load_from_arg(arg_data):
        return _fmm.FastMapMatchConfig_load_from_arg(arg_data)

    @staticmethod
    def register_arg(options):
        return _fmm.FastMapMatchConfig_register_arg(options)

    @staticmethod
    def register_help(oss):
        return _fmm.FastMapMatchConfig_register_help(oss)
    __swig_destroy__ = _fmm.delete_FastMapMatchConfig

# Register FastMapMatchConfig in _fmm:
_fmm.FastMapMatchConfig_swigregister(FastMapMatchConfig)

def FastMapMatchConfig_load_from_xml(xml_data):
    return _fmm.FastMapMatchConfig_load_from_xml(xml_data)

def FastMapMatchConfig_load_from_arg(arg_data):
    return _fmm.FastMapMatchConfig_load_from_arg(arg_data)

def FastMapMatchConfig_register_arg(options):
    return _fmm.FastMapMatchConfig_register_arg(options)

def FastMapMatchConfig_register_help(oss):
    return _fmm.FastMapMatchConfig_register_help(oss)

class FastMapMatch(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, network, graph, ubodt):
        _fmm.FastMapMatch_swiginit(self, _fmm.new_FastMapMatch(network, graph, ubodt))

    def match_traj(self, traj, config):
        return _fmm.FastMapMatch_match_traj(self, traj, config)

    def match_wkt(self, wkt, config):
        return _fmm.FastMapMatch_match_wkt(self, wkt, config)

    def match_gps_file(self, gps_config, result_config, config, use_omp=True):
        return _fmm.FastMapMatch_match_gps_file(self, gps_config, result_config, config, use_omp)
    __swig_destroy__ = _fmm.delete_FastMapMatch

# Register FastMapMatch in _fmm:
_fmm.FastMapMatch_swigregister(FastMapMatch)

class UBODTGenAlgorithm(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, network, graph):
        _fmm.UBODTGenAlgorithm_swiginit(self, _fmm.new_UBODTGenAlgorithm(network, graph))

    def generate_ubodt(self, filename, delta, binary=True, use_omp=True):
        return _fmm.UBODTGenAlgorithm_generate_ubodt(self, filename, delta, binary, use_omp)

    def precompute_ubodt_single_thead(self, filename, delta, binary=True):
        return _fmm.UBODTGenAlgorithm_precompute_ubodt_single_thead(self, filename, delta, binary)

    def precompute_ubodt_omp(self, filename, delta, binary=True):
        return _fmm.UBODTGenAlgorithm_precompute_ubodt_omp(self, filename, delta, binary)
    __swig_destroy__ = _fmm.delete_UBODTGenAlgorithm

# Register UBODTGenAlgorithm in _fmm:
_fmm.UBODTGenAlgorithm_swigregister(UBODTGenAlgorithm)

class GPSConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _fmm.GPSConfig_swiginit(self, _fmm.new_GPSConfig(*args))
    file = property(_fmm.GPSConfig_file_get, _fmm.GPSConfig_file_set)
    id = property(_fmm.GPSConfig_id_get, _fmm.GPSConfig_id_set)
    geom = property(_fmm.GPSConfig_geom_get, _fmm.GPSConfig_geom_set)
    x = property(_fmm.GPSConfig_x_get, _fmm.GPSConfig_x_set)
    y = property(_fmm.GPSConfig_y_get, _fmm.GPSConfig_y_set)
    timestamp = property(_fmm.GPSConfig_timestamp_get, _fmm.GPSConfig_timestamp_set)
    crs = property(_fmm.GPSConfig_crs_get, _fmm.GPSConfig_crs_set)
    gps_point = property(_fmm.GPSConfig_gps_point_get, _fmm.GPSConfig_gps_point_set)

    def validate(self):
        return _fmm.GPSConfig_validate(self)

    def get_gps_format(self):
        return _fmm.GPSConfig_get_gps_format(self)

    def to_string(self):
        return _fmm.GPSConfig_to_string(self)

    @staticmethod
    def load_from_xml(xml_data):
        return _fmm.GPSConfig_load_from_xml(xml_data)

    @staticmethod
    def load_from_arg(arg_data):
        return _fmm.GPSConfig_load_from_arg(arg_data)

    @staticmethod
    def register_arg(options):
        return _fmm.GPSConfig_register_arg(options)

    @staticmethod
    def register_help(oss):
        return _fmm.GPSConfig_register_help(oss)
    __swig_destroy__ = _fmm.delete_GPSConfig

# Register GPSConfig in _fmm:
_fmm.GPSConfig_swigregister(GPSConfig)

def GPSConfig_load_from_xml(xml_data):
    return _fmm.GPSConfig_load_from_xml(xml_data)

def GPSConfig_load_from_arg(arg_data):
    return _fmm.GPSConfig_load_from_arg(arg_data)

def GPSConfig_register_arg(options):
    return _fmm.GPSConfig_register_arg(options)

def GPSConfig_register_help(oss):
    return _fmm.GPSConfig_register_help(oss)

class OutputConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    write_opath = property(_fmm.OutputConfig_write_opath_get, _fmm.OutputConfig_write_opath_set)
    write_offset = property(_fmm.OutputConfig_write_offset_get, _fmm.OutputConfig_write_offset_set)
    write_error = property(_fmm.OutputConfig_write_error_get, _fmm.OutputConfig_write_error_set)
    write_cpath = property(_fmm.OutputConfig_write_cpath_get, _fmm.OutputConfig_write_cpath_set)
    write_tpath = property(_fmm.OutputConfig_write_tpath_get, _fmm.OutputConfig_write_tpath_set)
    write_mgeom = property(_fmm.OutputConfig_write_mgeom_get, _fmm.OutputConfig_write_mgeom_set)
    write_spdist = property(_fmm.OutputConfig_write_spdist_get, _fmm.OutputConfig_write_spdist_set)
    write_sp_dist = property(_fmm.OutputConfig_write_sp_dist_get, _fmm.OutputConfig_write_sp_dist_set)
    write_eu_dist = property(_fmm.OutputConfig_write_eu_dist_get, _fmm.OutputConfig_write_eu_dist_set)
    write_pgeom = property(_fmm.OutputConfig_write_pgeom_get, _fmm.OutputConfig_write_pgeom_set)
    write_ep = property(_fmm.OutputConfig_write_ep_get, _fmm.OutputConfig_write_ep_set)
    write_tp = property(_fmm.OutputConfig_write_tp_get, _fmm.OutputConfig_write_tp_set)
    write_trustworthiness = property(_fmm.OutputConfig_write_trustworthiness_get, _fmm.OutputConfig_write_trustworthiness_set)
    write_n_best_trustworthiness = property(_fmm.OutputConfig_write_n_best_trustworthiness_get, _fmm.OutputConfig_write_n_best_trustworthiness_set)
    write_cumu_prob = property(_fmm.OutputConfig_write_cumu_prob_get, _fmm.OutputConfig_write_cumu_prob_set)
    write_length = property(_fmm.OutputConfig_write_length_get, _fmm.OutputConfig_write_length_set)
    write_duration = property(_fmm.OutputConfig_write_duration_get, _fmm.OutputConfig_write_duration_set)
    write_speed = property(_fmm.OutputConfig_write_speed_get, _fmm.OutputConfig_write_speed_set)
    write_timestamp = property(_fmm.OutputConfig_write_timestamp_get, _fmm.OutputConfig_write_timestamp_set)
    write_candidates = property(_fmm.OutputConfig_write_candidates_get, _fmm.OutputConfig_write_candidates_set)

    def __init__(self):
        _fmm.OutputConfig_swiginit(self, _fmm.new_OutputConfig())
    __swig_destroy__ = _fmm.delete_OutputConfig

# Register OutputConfig in _fmm:
_fmm.OutputConfig_swigregister(OutputConfig)

class ResultConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    file = property(_fmm.ResultConfig_file_get, _fmm.ResultConfig_file_set)
    output_config = property(_fmm.ResultConfig_output_config_get, _fmm.ResultConfig_output_config_set)

    def validate(self):
        return _fmm.ResultConfig_validate(self)

    def to_string(self):
        return _fmm.ResultConfig_to_string(self)

    @staticmethod
    def string2set(s):
        return _fmm.ResultConfig_string2set(s)

    @staticmethod
    def load_from_xml(xml_data):
        return _fmm.ResultConfig_load_from_xml(xml_data)

    @staticmethod
    def load_from_arg(arg_data):
        return _fmm.ResultConfig_load_from_arg(arg_data)

    @staticmethod
    def register_arg(options):
        return _fmm.ResultConfig_register_arg(options)

    @staticmethod
    def register_help(oss):
        return _fmm.ResultConfig_register_help(oss)

    def __init__(self):
        _fmm.ResultConfig_swiginit(self, _fmm.new_ResultConfig())
    __swig_destroy__ = _fmm.delete_ResultConfig

# Register ResultConfig in _fmm:
_fmm.ResultConfig_swigregister(ResultConfig)

def ResultConfig_string2set(s):
    return _fmm.ResultConfig_string2set(s)

def ResultConfig_load_from_xml(xml_data):
    return _fmm.ResultConfig_load_from_xml(xml_data)

def ResultConfig_load_from_arg(arg_data):
    return _fmm.ResultConfig_load_from_arg(arg_data)

def ResultConfig_register_arg(options):
    return _fmm.ResultConfig_register_arg(options)

def ResultConfig_register_help(oss):
    return _fmm.ResultConfig_register_help(oss)

class STMATCHConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, k_arg=8, r_arg=300, gps_error_arg=50, vmax_arg=30, factor_arg=1.5, reverse_tolerance_arg=0.0):
        _fmm.STMATCHConfig_swiginit(self, _fmm.new_STMATCHConfig(k_arg, r_arg, gps_error_arg, vmax_arg, factor_arg, reverse_tolerance_arg))
    k = property(_fmm.STMATCHConfig_k_get, _fmm.STMATCHConfig_k_set)
    radius = property(_fmm.STMATCHConfig_radius_get, _fmm.STMATCHConfig_radius_set)
    gps_error = property(_fmm.STMATCHConfig_gps_error_get, _fmm.STMATCHConfig_gps_error_set)
    vmax = property(_fmm.STMATCHConfig_vmax_get, _fmm.STMATCHConfig_vmax_set)
    factor = property(_fmm.STMATCHConfig_factor_get, _fmm.STMATCHConfig_factor_set)
    reverse_tolerance = property(_fmm.STMATCHConfig_reverse_tolerance_get, _fmm.STMATCHConfig_reverse_tolerance_set)

    def validate(self):
        return _fmm.STMATCHConfig_validate(self)

    @staticmethod
    def load_from_xml(xml_data):
        return _fmm.STMATCHConfig_load_from_xml(xml_data)

    @staticmethod
    def load_from_arg(arg_data):
        return _fmm.STMATCHConfig_load_from_arg(arg_data)

    @staticmethod
    def register_arg(options):
        return _fmm.STMATCHConfig_register_arg(options)

    @staticmethod
    def register_help(oss):
        return _fmm.STMATCHConfig_register_help(oss)
    __swig_destroy__ = _fmm.delete_STMATCHConfig

# Register STMATCHConfig in _fmm:
_fmm.STMATCHConfig_swigregister(STMATCHConfig)

def STMATCHConfig_load_from_xml(xml_data):
    return _fmm.STMATCHConfig_load_from_xml(xml_data)

def STMATCHConfig_load_from_arg(arg_data):
    return _fmm.STMATCHConfig_load_from_arg(arg_data)

def STMATCHConfig_register_arg(options):
    return _fmm.STMATCHConfig_register_arg(options)

def STMATCHConfig_register_help(oss):
    return _fmm.STMATCHConfig_register_help(oss)

class STMATCH(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, network, graph):
        _fmm.STMATCH_swiginit(self, _fmm.new_STMATCH(network, graph))

    def match_wkt(self, wkt, config):
        return _fmm.STMATCH_match_wkt(self, wkt, config)

    def match_traj(self, traj, config):
        return _fmm.STMATCH_match_traj(self, traj, config)

    def match_gps_file(self, gps_config, result_config, config, use_omp=True):
        return _fmm.STMATCH_match_gps_file(self, gps_config, result_config, config, use_omp)
    __swig_destroy__ = _fmm.delete_STMATCH

# Register STMATCH in _fmm:
_fmm.STMATCH_swigregister(STMATCH)

class H3MatchResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    traj_id = property(_fmm.H3MatchResult_traj_id_get, _fmm.H3MatchResult_traj_id_set)
    hexs = property(_fmm.H3MatchResult_hexs_get, _fmm.H3MatchResult_hexs_set)

    def __init__(self):
        _fmm.H3MatchResult_swiginit(self, _fmm.new_H3MatchResult())
    __swig_destroy__ = _fmm.delete_H3MatchResult

# Register H3MatchResult in _fmm:
_fmm.H3MatchResult_swigregister(H3MatchResult)


def hexs2wkt(hexs, precision=12):
    return _fmm.hexs2wkt(hexs, precision)

def latlng2hex(lat, lng, level):
    return _fmm.latlng2hex(lat, lng, level)

def xy2hex(x, y, level):
    return _fmm.xy2hex(x, y, level)

def hex2wkt(index, precision=12):
    return _fmm.hex2wkt(index, precision)

def hexpath(start, end):
    return _fmm.hexpath(start, end)
class H3MMConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, h3level_arg=9, interpolate_arg=False):
        _fmm.H3MMConfig_swiginit(self, _fmm.new_H3MMConfig(h3level_arg, interpolate_arg))

    def validate(self):
        return _fmm.H3MMConfig_validate(self)

    def to_string(self):
        return _fmm.H3MMConfig_to_string(self)

    @staticmethod
    def load_from_arg(arg_data):
        return _fmm.H3MMConfig_load_from_arg(arg_data)

    @staticmethod
    def register_arg(options):
        return _fmm.H3MMConfig_register_arg(options)

    @staticmethod
    def register_help(oss):
        return _fmm.H3MMConfig_register_help(oss)
    h3level = property(_fmm.H3MMConfig_h3level_get, _fmm.H3MMConfig_h3level_set)
    interpolate = property(_fmm.H3MMConfig_interpolate_get, _fmm.H3MMConfig_interpolate_set)
    __swig_destroy__ = _fmm.delete_H3MMConfig

# Register H3MMConfig in _fmm:
_fmm.H3MMConfig_swigregister(H3MMConfig)

def H3MMConfig_load_from_arg(arg_data):
    return _fmm.H3MMConfig_load_from_arg(arg_data)

def H3MMConfig_register_arg(options):
    return _fmm.H3MMConfig_register_arg(options)

def H3MMConfig_register_help(oss):
    return _fmm.H3MMConfig_register_help(oss)

class H3MM(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def match_wkt(*args):
        return _fmm.H3MM_match_wkt(*args)

    @staticmethod
    def match_traj(traj, config):
        return _fmm.H3MM_match_traj(traj, config)

    @staticmethod
    def match_gps_file(gps_config, config, output_config, use_omp=True):
        return _fmm.H3MM_match_gps_file(gps_config, config, output_config, use_omp)

    def __init__(self):
        _fmm.H3MM_swiginit(self, _fmm.new_H3MM())
    __swig_destroy__ = _fmm.delete_H3MM

# Register H3MM in _fmm:
_fmm.H3MM_swigregister(H3MM)

def H3MM_match_wkt(*args):
    return _fmm.H3MM_match_wkt(*args)

def H3MM_match_traj(traj, config):
    return _fmm.H3MM_match_traj(traj, config)

def H3MM_match_gps_file(gps_config, config, output_config, use_omp=True):
    return _fmm.H3MM_match_gps_file(gps_config, config, output_config, use_omp)

class Matrix2d(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    m = property(_fmm.Matrix2d_m_get, _fmm.Matrix2d_m_set)

    def __init__(self, *args):
        _fmm.Matrix2d_swiginit(self, _fmm.new_Matrix2d(*args))

    def inverse(self):
        return _fmm.Matrix2d_inverse(self)

    def determinant(self):
        return _fmm.Matrix2d_determinant(self)
    __swig_destroy__ = _fmm.delete_Matrix2d

# Register Matrix2d in _fmm:
_fmm.Matrix2d_swigregister(Matrix2d)

class Vector2d(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    v = property(_fmm.Vector2d_v_get, _fmm.Vector2d_v_set)

    def __init__(self, x, y):
        _fmm.Vector2d_swiginit(self, _fmm.new_Vector2d(x, y))

    def __mul__(self, other):
        return _fmm.Vector2d___mul__(self, other)
    __swig_destroy__ = _fmm.delete_Vector2d

# Register Vector2d in _fmm:
_fmm.Vector2d_swigregister(Vector2d)

class CovarianceMatrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sde = property(_fmm.CovarianceMatrix_sde_get, _fmm.CovarianceMatrix_sde_set)
    sdn = property(_fmm.CovarianceMatrix_sdn_get, _fmm.CovarianceMatrix_sdn_set)
    sdu = property(_fmm.CovarianceMatrix_sdu_get, _fmm.CovarianceMatrix_sdu_set)
    sdne = property(_fmm.CovarianceMatrix_sdne_get, _fmm.CovarianceMatrix_sdne_set)
    sdeu = property(_fmm.CovarianceMatrix_sdeu_get, _fmm.CovarianceMatrix_sdeu_set)
    sdun = property(_fmm.CovarianceMatrix_sdun_get, _fmm.CovarianceMatrix_sdun_set)

    def to_2d_matrix(self):
        return _fmm.CovarianceMatrix_to_2d_matrix(self)

    def get_2d_uncertainty(self):
        return _fmm.CovarianceMatrix_get_2d_uncertainty(self)

    def __init__(self):
        _fmm.CovarianceMatrix_swiginit(self, _fmm.new_CovarianceMatrix())
    __swig_destroy__ = _fmm.delete_CovarianceMatrix

# Register CovarianceMatrix in _fmm:
_fmm.CovarianceMatrix_swigregister(CovarianceMatrix)

class CovarianceMapMatchConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, k_arg=8, min_candidates_arg=3, protection_level_multiplier_arg=1.0, reverse_tolerance=0.0, normalized_arg=True, use_mahalanobis_candidates_arg=True, window_length_arg=10, margin_used_trustworthiness_arg=True):
        _fmm.CovarianceMapMatchConfig_swiginit(self, _fmm.new_CovarianceMapMatchConfig(k_arg, min_candidates_arg, protection_level_multiplier_arg, reverse_tolerance, normalized_arg, use_mahalanobis_candidates_arg, window_length_arg, margin_used_trustworthiness_arg))
    k = property(_fmm.CovarianceMapMatchConfig_k_get, _fmm.CovarianceMapMatchConfig_k_set)
    min_candidates = property(_fmm.CovarianceMapMatchConfig_min_candidates_get, _fmm.CovarianceMapMatchConfig_min_candidates_set)
    protection_level_multiplier = property(_fmm.CovarianceMapMatchConfig_protection_level_multiplier_get, _fmm.CovarianceMapMatchConfig_protection_level_multiplier_set)
    reverse_tolerance = property(_fmm.CovarianceMapMatchConfig_reverse_tolerance_get, _fmm.CovarianceMapMatchConfig_reverse_tolerance_set)
    normalized = property(_fmm.CovarianceMapMatchConfig_normalized_get, _fmm.CovarianceMapMatchConfig_normalized_set)
    use_mahalanobis_candidates = property(_fmm.CovarianceMapMatchConfig_use_mahalanobis_candidates_get, _fmm.CovarianceMapMatchConfig_use_mahalanobis_candidates_set)
    window_length = property(_fmm.CovarianceMapMatchConfig_window_length_get, _fmm.CovarianceMapMatchConfig_window_length_set)
    margin_used_trustworthiness = property(_fmm.CovarianceMapMatchConfig_margin_used_trustworthiness_get, _fmm.CovarianceMapMatchConfig_margin_used_trustworthiness_set)

    def validate(self):
        return _fmm.CovarianceMapMatchConfig_validate(self)
    __swig_destroy__ = _fmm.delete_CovarianceMapMatchConfig

# Register CovarianceMapMatchConfig in _fmm:
_fmm.CovarianceMapMatchConfig_swigregister(CovarianceMapMatchConfig)

class CMMTrajectory(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_fmm.CMMTrajectory_id_get, _fmm.CMMTrajectory_id_set)
    geom = property(_fmm.CMMTrajectory_geom_get, _fmm.CMMTrajectory_geom_set)
    timestamps = property(_fmm.CMMTrajectory_timestamps_get, _fmm.CMMTrajectory_timestamps_set)
    covariances = property(_fmm.CMMTrajectory_covariances_get, _fmm.CMMTrajectory_covariances_set)
    protection_levels = property(_fmm.CMMTrajectory_protection_levels_get, _fmm.CMMTrajectory_protection_levels_set)

    def __init__(self, *args):
        _fmm.CMMTrajectory_swiginit(self, _fmm.new_CMMTrajectory(*args))

    def is_valid(self):
        return _fmm.CMMTrajectory_is_valid(self)
    __swig_destroy__ = _fmm.delete_CMMTrajectory

# Register CMMTrajectory in _fmm:
_fmm.CMMTrajectory_swigregister(CMMTrajectory)

class CandidateSearchResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    candidates = property(_fmm.CandidateSearchResult_candidates_get, _fmm.CandidateSearchResult_candidates_set)
    emission_probabilities = property(_fmm.CandidateSearchResult_emission_probabilities_get, _fmm.CandidateSearchResult_emission_probabilities_set)

    def __init__(self):
        _fmm.CandidateSearchResult_swiginit(self, _fmm.new_CandidateSearchResult())
    __swig_destroy__ = _fmm.delete_CandidateSearchResult

# Register CandidateSearchResult in _fmm:
_fmm.CandidateSearchResult_swigregister(CandidateSearchResult)

class CovarianceMapMatch(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, network, graph, ubodt):
        _fmm.CovarianceMapMatch_swiginit(self, _fmm.new_CovarianceMapMatch(network, graph, ubodt))

    def match_traj(self, *args):
        return _fmm.CovarianceMapMatch_match_traj(self, *args)

    def match_gps_file(self, gps_config, result_config, config, convert_to_projected, use_omp=True):
        return _fmm.CovarianceMapMatch_match_gps_file(self, gps_config, result_config, config, convert_to_projected, use_omp)
    __swig_destroy__ = _fmm.delete_CovarianceMapMatch

# Register CovarianceMapMatch in _fmm:
_fmm.CovarianceMapMatch_swigregister(CovarianceMapMatch)

class UBODTManager(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def getInstance():
        return _fmm.UBODTManager_getInstance()

    def get_ubodt(self, filename, multiplier=1, force_reload=False):
        return _fmm.UBODTManager_get_ubodt(self, filename, multiplier, force_reload)

    def get_partial_ubodt(self, *args):
        return _fmm.UBODTManager_get_partial_ubodt(self, *args)

    def get_cached_ubodt(self, filename, cache_size=10000, multiplier=1, force_reload=False):
        return _fmm.UBODTManager_get_cached_ubodt(self, filename, cache_size, multiplier, force_reload)

    def is_loaded(self, filename):
        return _fmm.UBODTManager_is_loaded(self, filename)

    def release_ubodt(self, filename):
        return _fmm.UBODTManager_release_ubodt(self, filename)

    def release_all(self):
        return _fmm.UBODTManager_release_all(self)

    def get_stats(self):
        return _fmm.UBODTManager_get_stats(self)

    def print_status(self):
        return _fmm.UBODTManager_print_status(self)

    def set_auto_release(self, enable):
        return _fmm.UBODTManager_set_auto_release(self, enable)

    def get_auto_release(self):
        return _fmm.UBODTManager_get_auto_release(self)

    @staticmethod
    def check_daemon_loaded(filename):
        return _fmm.UBODTManager_check_daemon_loaded(filename)

# Register UBODTManager in _fmm:
_fmm.UBODTManager_swigregister(UBODTManager)

def UBODTManager_getInstance():
    return _fmm.UBODTManager_getInstance()

def UBODTManager_check_daemon_loaded(filename):
    return _fmm.UBODTManager_check_daemon_loaded(filename)


def load_ubodt(filename, multiplier=1, keep=True):
    return _fmm.load_ubodt(filename, multiplier, keep)

def load_partial_ubodt(filename, network, trajectories, buffer_ratio=0.1, keep=True):
    return _fmm.load_partial_ubodt(filename, network, trajectories, buffer_ratio, keep)

def load_cached_ubodt(filename, cache_size=10000, multiplier=1, keep=True):
    return _fmm.load_cached_ubodt(filename, cache_size, multiplier, keep)

def release_ubodt(filename):
    return _fmm.release_ubodt(filename)

def release_all_ubodts():
    return _fmm.release_all_ubodts()

def is_ubodt_loaded(filename):
    return _fmm.is_ubodt_loaded(filename)

def print_ubodt_status():
    return _fmm.print_ubodt_status()


