#!/usr/bin/env python3
"""
Visualise ground truth trajectories atop the base road network.

Example usage:
    python python/plot_ground_truth.py \\
        --ground-truth tmp/cmm_test5/ground_truth.csv \\
        --network input/map/haikou/edges.shp \\
        --output tmp/cmm_test5/ground_truth.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import shapely.wkt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot ground truth trajectories on the road network.")
    parser.add_argument("--ground-truth", type=Path, required=True,
                        help="CSV generated by generate_data_cmm.py containing ground truth trajectories.")
    parser.add_argument("--network", type=Path, required=True,
                        help="Shapefile (or other vector source) with the road network geometry.")
    parser.add_argument("--output", type=Path, required=True,
                        help="Destination PNG file.")
    parser.add_argument("--dpi", type=int, default=150, help="Output image resolution.")
    parser.add_argument("--figsize", type=float, nargs=2, default=(10.0, 10.0),
                        metavar=("WIDTH", "HEIGHT"),
                        help="Figure size in inches (width height).")
    parser.add_argument("--trajectory-alpha", type=float, default=0.95,
                        help="Transparency for trajectories.")
    parser.add_argument("--road-alpha", type=float, default=0.6,
                        help="Transparency for road network.")
    return parser.parse_args()


def load_ground_truth(path: Path) -> gpd.GeoDataFrame:
    df = pd.read_csv(path, delimiter=";")
    if "geom" not in df.columns:
        raise ValueError("ground truth CSV must contain a 'geom' column with WKT LineStrings")
    df["geometry"] = df["geom"].map(shapely.wkt.loads)
    gdf = gpd.GeoDataFrame(df, geometry="geometry", crs="EPSG:4326")
    return gdf


def load_network(path: Path) -> gpd.GeoDataFrame:
    gdf = gpd.read_file(path)
    if gdf.crs is None:
        raise ValueError(f"Network file {path} missing CRS information")
    return gdf.to_crs("EPSG:4326")


def plot_ground_truth(ground_truth: gpd.GeoDataFrame,
                      network: gpd.GeoDataFrame,
                      output: Path,
                      dpi: int,
                      figsize: tuple[float, float],
                      trajectory_alpha: float,
                      road_alpha: float) -> None:
    fig, ax = plt.subplots(figsize=figsize)

    network.plot(ax=ax, color="#b0b0b0", linewidth=0.5, alpha=road_alpha)

    # Choose colours per trajectory using a categorical palette.
    try:
        import seaborn as sns  # type: ignore

        palette = sns.color_palette("husl", len(ground_truth))
    except ImportError:
        palette = plt.cm.get_cmap("tab20", len(ground_truth))

    for idx, (_, row) in enumerate(ground_truth.iterrows()):
        color = palette[idx] if isinstance(palette, list) else palette(idx)
        ground_truth.loc[[row.name]].plot(
            ax=ax,
            color=color,
            linewidth=2.0,
            alpha=trajectory_alpha,
            label=f"ID {row['id']}",
        )

    ax.set_aspect("equal")
    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")
    ax.set_title("Ground Truth Trajectories")
    ax.legend(loc="best", fontsize="small")
    ax.grid(True, linestyle=":", linewidth=0.3, alpha=0.4)

    output.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    fig.savefig(output, dpi=dpi)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    ground_truth = load_ground_truth(args.ground_truth)
    network = load_network(args.network)
    plot_ground_truth(
        ground_truth,
        network,
        args.output,
        args.dpi,
        tuple(args.figsize),
        args.trajectory_alpha,
        args.road_alpha,
    )
    print(f"Saved ground truth visualisation -> {args.output}")


if __name__ == "__main__":
    main()
